#!/bin/bash

cd /home/mainsail

if ! [ -d "mainsail" ]; then
    su -c "wget https://github.com/mainsail-crew/mainsail/releases/latest/download/mainsail.zip"
    su -c "mkdir mainsail"
    su -c "unzip -o -d mainsail mainsail.zip"
fi

if ! [ -f "has_run" ]; then
    touch has_run
    mkdir -p /home/mainsail/klipper_logs
    sudo chown -hR mainsail:mainsail /home/mainsail
fi

nginx -t
nginx -g "daemon off;"
