#!/bin/bash

cd /home/mainsail

if ! [ -d "mainsail" ]; then
    wget https://github.com/mainsail-crew/mainsail/releases/latest/download/mainsail.zip
    mkdir mainsail
    unzip -o -d mainsail mainsail.zip
fi

if ! [ -f "has_run" ]; then
    touch has_run
    sudo chown -hR mainsail:mainsail mainsail
fi

nginx -t
nginx -g "daemon off;"
